baseURL = 'https://tree.wintervale.me/'
languageCode = 'en-us'
title = "Wintervale's Tree of Direction"
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

copyright = "greetings from [renavi](https://wintervale.me) and the inner circle."
description = "At the center of town stands a tree with signs pointing many which ways..."

[params]
  attribution = false
  description = "At the center of town stands a tree with signs pointing many which ways..."

[params.author]
  name = "Wintervale's Tree of Direction"
  headline = "At the center of town stands a tree with signs pointing many which ways..."
  image = "sigil.png"
  links = [
    { self = { href = "https://wintervale.me", text = "Self" }},
    { projects = { href = "/projects", text = "Project", target = "_self" } },
    { socials = { href = "/socials", text = "Social", target = "_self" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
